[package]
name = "door_trigger"
version = "0.1.0"
authors = ["Gary <gsuyemoto@gmail.com"]
edition = "2018"

[dependencies]
rust_gpiozero = "0.2.0"
soloud = { version = "0.3" }
glob = "0.3.0"
fastrand = "1.4.0"
